# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

defaults:
  run:
    shell: bash

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build
        run: |
          bash semver.sh
          pyinstaller -y decoder.spec

      - name: Linux rename
        if: ${{ matrix.os }} == 'ubuntu-latest'
        run: mv dist/GeoscanDecoder dist/GeoscanDecoder_linux

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: GeoscanDecoder_${{ matrix.os }}
          path: dist/*

  build7:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build
        run: |
          bash semver.sh
          pyinstaller -y decoder.spec
          mv dist/GeoscanDecoder.exe dist/GeoscanDecoder_win7.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: GeoscanDecoder_win7
          path: dist/*

  nightly_release:
    runs-on: ubuntu-latest
    needs: ["build", "build7"]

    steps:
      - uses: actions/download-artifact@v3

      - name: Collect
        run: |
          mkdir out &&
          cp GeoscanDecoder_*/* out/

      - name: Update release
        run: gh release upload nightly out/* -R ${{ github.repository }} --clobber
